version: '3'

networks:
  github:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/16
volumes:
    github_docker_certs:
    #github_docker_dind:

services:
  runner1:
    image: "harbor.vuitton.net/github/github-runner-base:withazurecli"
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '1'
    restart: always
    depends_on:
      - docker
    volumes:
      - github_docker_certs:/certs/client:ro
      - type: "bind"
        source: "/data/github_runner1"
        target: "/runner"
    environment:
      RUNNER_ORG: "LouisVuitton"
      ACCESS_TOKEN: "${RUNNER_CFG_PAT}"
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 0
      RUNNER_NAME: "azure-vm-runner-1"
      RUNNER_LABELS: "azure,vm,testing,compose-self-hosted"
      RUNNER_GROUP: "azure-vm"
    command: "'rm -fR /runner/_*;entrypoint.sh'"
    extra_hosts:
      - "api.github.com:140.82.121.6"
      - "github.com:140.82.121.3"
      - "docs.github.com:185.199.111.154"
      - "codeload.github.com:140.82.121.9"
      - "github.githubassets.com:185.199.109.154"
      - "objects.githubusercontent.com:185.199.110.133"
      - "objects-origin.githubusercontent.com:140.82.112.22"
      - "github-releases.githubusercontent.com:185.199.108.154"
      - "github-registry-files.githubusercontent.com:185.199.110.154"
      - "ghcr.io:140.82.121.34"
      - "louisvuitton-expertise.actions.githubusercontent.com:13.107.42.16"
      - "louisvuitton-expertise.pkg.github.com:140.82.121.33"
      - "lvstopocdcxitroadmap.privatelink.blob.core.windows.net:10.55.244.21"
      - "login.microsoftonline.com:40.126.31.71"
      - "harbor.vuitton.net:10.55.10.55"
      - "harbor-prj.vuitton.net:10.55.16.110"

  docker:
    image: harbor.vuitton.net/lvm/trmdind:1.0
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: '/certs'
    volumes:
      - github_docker_certs:/certs/client
#      - github_docker_dind:/var/lib/docker
      - type: "bind"
        source: "/data/github_docker_dind"
        target: "/var/lib/docker"
    ports:
      - 2376:2376
    extra_hosts:
      - "mcr.microsoft.com:204.79.197.219"
      - "harbor.vuitton.net:10.55.10.55"
      - "harbor-prj.vuitton.net:10.55.16.110"
      - "ghcr.io:140.82.121.34"
